name: Ejecutar script PowerShell

on:
  push:
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ejecutar script PowerShell
        shell: pwsh
        run: ./holamundo.ps1
